---
# vars file for k8s
# /etc/hosts主节点和工作节点的映射关系
master_hostsip:
  "192.168.1.155": "k8s-master01"
  "192.168.1.156": "k8s-master02"
  "192.168.1.157": "k8s-master03"
node_hostsip:
  "192.168.1.158": "k8s-node01"
  "192.168.1.159": "k8s-node02"
# /etc/hosts负载均衡vip地址
lb_hosts_to_add:
  "192.168.1.160": "k8s-master-lb"

# service ip
#service_ip:
#  - "10.96.0.1"
service_ip: "10.96.0.1"
# pod容器ip
pod_ip: "172.30.0.0/16"

# 生产etcd证书时使用，etcd的节点主机名和对应ip, 这里使用的master节点
etcd_hostsip:
  "192.168.1.155": "k8s-master01"
  "192.168.1.156": "k8s-master02"
  "192.168.1.157": "k8s-master03"

config_limit_vars:
  -  "* soft nofile 65536"
  -  "* hard nofile 131072"
  -  "* soft nproc 65535"
  -  "* hard nproc 655350"
  -  "* soft memlock unlimited"
  -  "* hard memlock unlimited"

stop_service:
  - "firewalld"
  - "dnsmasq"
  - 'NetworkManager'

kernel_upgrade_packages:
        #"http://193.49.22.109/elrepo/kernel/el7/x86_64/RPMS/kernel-ml-devel-4.19.12-1.el7.elrepo.x86_64.rpm": "/root/kernel-ml-devel-4.19.12-1.el7.elrepo.x86_64.rpm"
        #"http://193.49.22.109/elrepo/kernel/el7/x86_64/RPMS/kernel-ml-4.19.12-1.el7.elrepo.x86_64.rpm": "/root/kernel-ml-4.19.12-1.el7.elrepo.x86_64.rpm"
  "http://download.it.novaecs.com/k8s/kernel-ml-devel-4.19.12-1.el7.elrepo.x86_64.rpm": "/root/kernel-ml-devel-4.19.12-1.el7.elrepo.x86_64.rpm"
  "http://download.it.novaecs.com/k8s/kernel-ml-4.19.12-1.el7.elrepo.x86_64.rpm": "/root/kernel-ml-4.19.12-1.el7.elrepo.x86_64.rpm"
config_ipvs_vars:
  -  "ip_vs"
  -  "ip_vs_lc"
  -  "ip_vs_wlc"
  -  "ip_vs_rr"
  -  "ip_vs_wrr"
  -  "ip_vs_lblc"
  -  "ip_vs_lblcr"
  -  "ip_vs_dh"
  -  "ip_vs_sh"
  -  "ip_vs_fo"
  -  "ip_vs_nq"
  -  "ip_vs_sed"
  -  "ip_vs_ftp"
  -  "ip_vs_sh"
  -  "nf_conntrack"
  -  "ip_tables"
  -  "ip_set"
  -  "xt_set"
  -  "ipt_set"
  -  "ipt_rpfilter"
  -  "ipt_REJECT"
  -  "ipip"
install_k8s_etcd_packages:
        #"https://dl.k8s.io/v1.27.4/kubernetes-server-linux-amd64.tar.gz": "/usr/local/kubernetes-server-linux-amd64.tar.gz"
        #  "https://github.com/etcd-io/etcd/releases/download/v3.5.7/etcd-v3.5.7-linux-amd64.tar.gz": "/usr/local/etcd-v3.5.7-linux-amd64.tar.gz"
  "http://download.it.novaecs.com/k8s/kubernetes-server-linux-amd64.tar.gz": "/usr/local/kubernetes-server-linux-amd64.tar.gz"
  "http://download.it.novaecs.com/k8s/etcd-v3.5.7-linux-amd64.tar.gz": "/usr/local/etcd-v3.5.7-linux-amd64.tar.gz"

cert_tools:
  "files/cfssl_linux-amd64": "/usr/local/bin/cfssl"
  "files/cfssljson_linux-amd64": "/usr/local/bin/cfssljson"
ha_keepalived:
  - "haproxy"
  - "keepalived"


